### ISSUE TITLE
flake8 errors for topic_modeling.py

### ISSUE THREAD

**Issue by ceduze** [heybaebae/news_analyzer#10]
news-article-nlp/libraries/topic_modeling.py:9:1: F401 'text_processing' imported but unused
news-article-nlp/libraries/topic_modeling.py:11:1: E302 expected 2 blank lines, found 1
news-article-nlp/libraries/topic_modeling.py:29:1: E302 expected 2 blank lines, found 1
news-article-nlp/libraries/topic_modeling.py:52:1: E302 expected 2 blank lines, found 1
news-article-nlp/libraries/topic_modeling.py:67:1: E302 expected 2 blank lines, found 1
news-article-nlp/libraries/topic_modeling.py:80:1: E302 expected 2 blank lines, found 1
news-article-nlp/libraries/topic_modeling.py:98:80: E501 line too long (85 > 79 characters)
news-article-nlp/libraries/topic_modeling.py:100:80: E501 line too long (85 > 79 characters)
news-article-nlp/libraries/topic_modeling.py:112:36: W291 trailing whitespace
news-article-nlp/libraries/topic_modeling.py:113:31: W291 trailing whitespace
news-article-nlp/libraries/topic_modeling.py:127:80: E501 line too long (93 > 79 characters)
news-article-nlp/libraries/topic_modeling.py:135:80: E501 line too long (100 > 79 characters)
news-article-nlp/libraries/topic_modeling.py:137:64: W291 trailing whitespace
news-article-nlp/libraries/topic_modeling.py:139:72: W291 trailing whitespace
news-article-nlp/libraries/topic_modeling.py:144:80: E501 line too long (83 > 79 characters)
news-article-nlp/libraries/topic_modeling.py:144:84: W291 trailing whitespace
news-article-nlp/libraries/topic_modeling.py:145:17: E128 continuation line under-indented for visual indent
news-article-nlp/libraries/topic_modeling.py:150:1: E302 expected 2 blank lines, found 1
news-article-nlp/libraries/topic_modeling.py:177:80: E501 line too long (85 > 79 characters)
news-article-nlp/libraries/topic_modeling.py:178:80: E501 line too long (89 > 79 characters)
news-article-nlp/libraries/topic_modeling.py:188:17: E128 continuation line under-indented for visual indent
news-article-nlp/libraries/topic_modeling.py:197:21: F841 local variable 'best_n_topics' is assigned to but never used
news-article-nlp/libraries/topic_modeling.py:200:31: F821 undefined name 'loglikelihoods'

**Comment by heybaebae** [comment]
completed, module passes all flake8 tests.
