### ISSUE TITLE
flake8 errors for build_resources.py

### ISSUE THREAD

**Issue by ceduze** [heybaebae/news_analyzer#11]
news-article-nlp/scripts/build_resources.py:11:1: F401 'requests' imported but unused
news-article-nlp/scripts/build_resources.py:17:1: F401 'numpy as np' imported but unused
news-article-nlp/scripts/build_resources.py:20:1: E402 module level import not at top of file
news-article-nlp/scripts/build_resources.py:21:1: E402 module level import not at top of file
news-article-nlp/scripts/build_resources.py:22:1: E402 module level import not at top of file
news-article-nlp/scripts/build_resources.py:24:1: E266 too many leading '#' for block comment
news-article-nlp/scripts/build_resources.py:36:1: E302 expected 2 blank lines, found 1
news-article-nlp/scripts/build_resources.py:46:1: E302 expected 2 blank lines, found 1
news-article-nlp/scripts/build_resources.py:60:80: E501 line too long (80 > 79 characters)
news-article-nlp/scripts/build_resources.py:65:1: E305 expected 2 blank lines after class or function definition, found 1
news-article-nlp/scripts/build_resources.py:71:80: E501 line too long (103 > 79 characters)
news-article-nlp/scripts/build_resources.py:90:18: F821 undefined name 'nytimes_article_retriever'
news-article-nlp/scripts/build_resources.py:90:69: E261 at least two spaces before inline comment
news-article-nlp/scripts/build_resources.py:90:80: E501 line too long (84 > 79 characters)
news-article-nlp/scripts/build_resources.py:90:85: W291 trailing whitespace
news-article-nlp/scripts/build_resources.py:91:80: E501 line too long (93 > 79 characters)
news-article-nlp/scripts/build_resources.py:96:80: E501 line too long (103 > 79 characters)
news-article-nlp/scripts/build_resources.py:96:82: F821 undefined name 'RANDOM_STATE'
news-article-nlp/scripts/build_resources.py:96:96: F821 undefined name 'REFRESH'
news-article-nlp/scripts/build_resources.py:97:80: E501 line too long (85 > 79 characters)
news-article-nlp/scripts/build_resources.py:101:80: E501 line too long (107 > 79 characters)
news-article-nlp/scripts/build_resources.py:101:86: F821 undefined name 'RANDOM_STATE'
news-article-nlp/scripts/build_resources.py:101:100: F821 undefined name 'REFRESH'
news-article-nlp/scripts/build_resources.py:105:45: E261 at least two spaces before inline comment
news-article-nlp/scripts/build_resources.py:105:80: E501 line too long (100 > 79 characters)
news-article-nlp/scripts/build_resources.py:111:21: F821 undefined name 'words'

**Comment by ryanbae89** [comment]
all fixed, along with constant variables
