### ISSUE TITLE
flake8 errors for test_handler.py

### ISSUE THREAD

**Issue by ceduze** [heybaebae/news_analyzer#13]
news-article-nlp/tests/test_handler.py:6:1: E402 module level import not at top of file
news-article-nlp/tests/test_handler.py:8:1: E302 expected 2 blank lines, found 1
news-article-nlp/tests/test_handler.py:10:1: W191 indentation contains tabs
news-article-nlp/tests/test_handler.py:11:1: W191 indentation contains tabs
news-article-nlp/tests/test_handler.py:12:1: W191 indentation contains tabs
news-article-nlp/tests/test_handler.py:13:1: W191 indentation contains tabs
news-article-nlp/tests/test_handler.py:15:1: W191 indentation contains tabs
news-article-nlp/tests/test_handler.py:16:1: W191 indentation contains tabs
news-article-nlp/tests/test_handler.py:16:80: E501 line too long (81 > 79 characters)
news-article-nlp/tests/test_handler.py:17:1: W191 indentation contains tabs
news-article-nlp/tests/test_handler.py:19:1: W191 indentation contains tabs
news-article-nlp/tests/test_handler.py:20:1: W191 indentation contains tabs
news-article-nlp/tests/test_handler.py:20:80: E501 line too long (80 > 79 characters)
news-article-nlp/tests/test_handler.py:21:1: W191 indentation contains tabs
news-article-nlp/tests/test_handler.py:23:1: W191 indentation contains tabs
news-article-nlp/tests/test_handler.py:24:1: W191 indentation contains tabs
news-article-nlp/tests/test_handler.py:24:80: E501 line too long (96 > 79 characters)
news-article-nlp/tests/test_handler.py:25:1: W191 indentation contains tabs
news-article-nlp/tests/test_handler.py:29:1: E101 indentation contains mixed spaces and tabs
news-article-nlp/tests/test_handler.py:29:20: W292 no newline at end of file

**Comment by heybaebae** [comment]
has issues with the first error:
news-article-nlp/tests/test_handler.py:6:1: E402 module level import not at top of file

due to our sys.path.append() and importing handler afterwards. Can discuss on Sunday.

**Comment by ceduze** [comment]
Thanks. I found a fix
