### ISSUE TITLE
flake8 errors for test_topic_modeling.py

### ISSUE THREAD

**Issue by ceduze** [heybaebae/news_analyzer#15]
news-article-nlp/tests/test_topic_modeling.py:6:1: E402 module level import not at top of file
news-article-nlp/tests/test_topic_modeling.py:7:1: E402 module level import not at top of file
news-article-nlp/tests/test_topic_modeling.py:7:19: W291 trailing whitespace
news-article-nlp/tests/test_topic_modeling.py:8:1: E402 module level import not at top of file
news-article-nlp/tests/test_topic_modeling.py:9:1: E402 module level import not at top of file
news-article-nlp/tests/test_topic_modeling.py:10:1: E402 module level import not at top of file
news-article-nlp/tests/test_topic_modeling.py:11:1: E402 module level import not at top of file
news-article-nlp/tests/test_topic_modeling.py:13:1: E302 expected 2 blank lines, found 1
news-article-nlp/tests/test_topic_modeling.py:16:1: W191 indentation contains tabs
news-article-nlp/tests/test_topic_modeling.py:17:1: W191 indentation contains tabs
news-article-nlp/tests/test_topic_modeling.py:18:1: W191 indentation contains tabs
news-article-nlp/tests/test_topic_modeling.py:19:1: W191 indentation contains tabs
news-article-nlp/tests/test_topic_modeling.py:19:80: E501 line too long (86 > 79 characters)
news-article-nlp/tests/test_topic_modeling.py:20:1: W191 indentation contains tabs
news-article-nlp/tests/test_topic_modeling.py:20:80: E501 line too long (94 > 79 characters)
news-article-nlp/tests/test_topic_modeling.py:21:1: W191 indentation contains tabs
news-article-nlp/tests/test_topic_modeling.py:22:1: W191 indentation contains tabs
news-article-nlp/tests/test_topic_modeling.py:23:1: W191 indentation contains tabs
news-article-nlp/tests/test_topic_modeling.py:24:1: W191 indentation contains tabs
news-article-nlp/tests/test_topic_modeling.py:24:79: W291 trailing whitespace
news-article-nlp/tests/test_topic_modeling.py:25:1: W191 indentation contains tabs
news-article-nlp/tests/test_topic_modeling.py:25:4: E128 continuation line under-indented for visual indent
news-article-nlp/tests/test_topic_modeling.py:26:1: W191 indentation contains tabs
news-article-nlp/tests/test_topic_modeling.py:26:80: E501 line too long (84 > 79 characters)
news-article-nlp/tests/test_topic_modeling.py:28:1: W191 indentation contains tabs
news-article-nlp/tests/test_topic_modeling.py:30:1: W191 indentation contains tabs
news-article-nlp/tests/test_topic_modeling.py:31:1: W191 indentation contains tabs
news-article-nlp/tests/test_topic_modeling.py:32:1: W191 indentation contains tabs
news-article-nlp/tests/test_topic_modeling.py:33:1: W191 indentation contains tabs
news-article-nlp/tests/test_topic_modeling.py:34:1: W191 indentation contains tabs
news-article-nlp/tests/test_topic_modeling.py:35:1: W191 indentation contains tabs
news-article-nlp/tests/test_topic_modeling.py:36:1: W191 indentation contains tabs
news-article-nlp/tests/test_topic_modeling.py:37:1: W191 indentation contains tabs
news-article-nlp/tests/test_topic_modeling.py:38:1: W191 indentation contains tabs
news-article-nlp/tests/test_topic_modeling.py:39:1: W191 indentation contains tabs
news-article-nlp/tests/test_topic_modeling.py:41:1: W191 indentation contains tabs
news-article-nlp/tests/test_topic_modeling.py:42:1: W191 indentation contains tabs
news-article-nlp/tests/test_topic_modeling.py:43:1: W191 indentation contains tabs
news-article-nlp/tests/test_topic_modeling.py:43:51: W291 trailing whitespace
news-article-nlp/tests/test_topic_modeling.py:45:1: W191 indentation contains tabs
news-article-nlp/tests/test_topic_modeling.py:46:1: W191 indentation contains tabs
news-article-nlp/tests/test_topic_modeling.py:47:1: W191 indentation contains tabs
news-article-nlp/tests/test_topic_modeling.py:49:1: W191 indentation contains tabs
news-article-nlp/tests/test_topic_modeling.py:51:1: W191 indentation contains tabs
news-article-nlp/tests/test_topic_modeling.py:52:1: W191 indentation contains tabs
news-article-nlp/tests/test_topic_modeling.py:53:1: W191 indentation contains tabs
news-article-nlp/tests/test_topic_modeling.py:54:1: W191 indentation contains tabs
news-article-nlp/tests/test_topic_modeling.py:55:1: W191 indentation contains tabs
news-article-nlp/tests/test_topic_modeling.py:55:75: E502 the backslash is redundant between brackets
news-article-nlp/tests/test_topic_modeling.py:56:1: W191 indentation contains tabs
news-article-nlp/tests/test_topic_modeling.py:56:4: E128 continuation line under-indented for visual indent
news-article-nlp/tests/test_topic_modeling.py:57:1: W191 indentation contains tabs
news-article-nlp/tests/test_topic_modeling.py:58:1: W191 indentation contains tabs
news-article-nlp/tests/test_topic_modeling.py:59:1: W191 indentation contains tabs
news-article-nlp/tests/test_topic_modeling.py:60:1: W191 indentation contains tabs
news-article-nlp/tests/test_topic_modeling.py:60:75: E502 the backslash is redundant between brackets
news-article-nlp/tests/test_topic_modeling.py:61:1: W191 indentation contains tabs
news-article-nlp/tests/test_topic_modeling.py:61:4: E128 continuation line under-indented for visual indent
news-article-nlp/tests/test_topic_modeling.py:62:1: W191 indentation contains tabs
news-article-nlp/tests/test_topic_modeling.py:63:1: W191 indentation contains tabs
news-article-nlp/tests/test_topic_modeling.py:64:1: W191 indentation contains tabs
news-article-nlp/tests/test_topic_modeling.py:64:48: W291 trailing whitespace
news-article-nlp/tests/test_topic_modeling.py:65:1: W191 indentation contains tabs
news-article-nlp/tests/test_topic_modeling.py:65:16: E231 missing whitespace after ','
news-article-nlp/tests/test_topic_modeling.py:65:18: E231 missing whitespace after ','
news-article-nlp/tests/test_topic_modeling.py:66:1: W191 indentation contains tabs
news-article-nlp/tests/test_topic_modeling.py:67:1: W191 indentation contains tabs
news-article-nlp/tests/test_topic_modeling.py:67:80: E501 line too long (83 > 79 characters)
news-article-nlp/tests/test_topic_modeling.py:67:83: E502 the backslash is redundant between brackets
news-article-nlp/tests/test_topic_modeling.py:68:1: W191 indentation contains tabs
news-article-nlp/tests/test_topic_modeling.py:68:4: E128 continuation line under-indented for visual indent
news-article-nlp/tests/test_topic_modeling.py:69:1: W191 indentation contains tabs
news-article-nlp/tests/test_topic_modeling.py:70:1: W191 indentation contains tabs
news-article-nlp/tests/test_topic_modeling.py:70:70: W291 trailing whitespace
news-article-nlp/tests/test_topic_modeling.py:71:1: W191 indentation contains tabs
news-article-nlp/tests/test_topic_modeling.py:71:4: E128 continuation line under-indented for visual indent
news-article-nlp/tests/test_topic_modeling.py:72:1: W191 indentation contains tabs
news-article-nlp/tests/test_topic_modeling.py:73:1: W191 indentation contains tabs
news-article-nlp/tests/test_topic_modeling.py:74:1: W191 indentation contains tabs
news-article-nlp/tests/test_topic_modeling.py:75:1: W191 indentation contains tabs
news-article-nlp/tests/test_topic_modeling.py:75:70: W291 trailing whitespace
news-article-nlp/tests/test_topic_modeling.py:76:1: W191 indentation contains tabs
news-article-nlp/tests/test_topic_modeling.py:76:4: E128 continuation line under-indented for visual indent
news-article-nlp/tests/test_topic_modeling.py:77:1: W191 indentation contains tabs
news-article-nlp/tests/test_topic_modeling.py:77:48: W291 trailing whitespace
news-article-nlp/tests/test_topic_modeling.py:78:1: W191 indentation contains tabs
news-article-nlp/tests/test_topic_modeling.py:78:52: W291 trailing whitespace
news-article-nlp/tests/test_topic_modeling.py:79:1: W191 indentation contains tabs
news-article-nlp/tests/test_topic_modeling.py:79:5: E128 continuation line under-indented for visual indent
news-article-nlp/tests/test_topic_modeling.py:80:1: W191 indentation contains tabs
news-article-nlp/tests/test_topic_modeling.py:80:64: E502 the backslash is redundant between brackets
news-article-nlp/tests/test_topic_modeling.py:81:1: W191 indentation contains tabs
news-article-nlp/tests/test_topic_modeling.py:81:4: E128 continuation line under-indented for visual indent
news-article-nlp/tests/test_topic_modeling.py:82:1: W191 indentation contains tabs
news-article-nlp/tests/test_topic_modeling.py:82:48: W291 trailing whitespace
news-article-nlp/tests/test_topic_modeling.py:83:1: W191 indentation contains tabs
news-article-nlp/tests/test_topic_modeling.py:83:52: W291 trailing whitespace
news-article-nlp/tests/test_topic_modeling.py:84:1: W191 indentation contains tabs
news-article-nlp/tests/test_topic_modeling.py:84:5: E128 continuation line under-indented for visual indent
news-article-nlp/tests/test_topic_modeling.py:85:1: W191 indentation contains tabs
news-article-nlp/tests/test_topic_modeling.py:85:63: E502 the backslash is redundant between brackets
news-article-nlp/tests/test_topic_modeling.py:86:1: W191 indentation contains tabs
news-article-nlp/tests/test_topic_modeling.py:86:4: E128 continuation line under-indented for visual indent
news-article-nlp/tests/test_topic_modeling.py:87:1: W191 indentation contains tabs
news-article-nlp/tests/test_topic_modeling.py:87:70: W291 trailing whitespace
news-article-nlp/tests/test_topic_modeling.py:88:1: W191 indentation contains tabs
news-article-nlp/tests/test_topic_modeling.py:88:4: E128 continuation line under-indented for visual indent
news-article-nlp/tests/test_topic_modeling.py:89:1: W191 indentation contains tabs
news-article-nlp/tests/test_topic_modeling.py:89:48: W291 trailing whitespace
news-article-nlp/tests/test_topic_modeling.py:90:1: W191 indentation contains tabs
news-article-nlp/tests/test_topic_modeling.py:90:52: W291 trailing whitespace
news-article-nlp/tests/test_topic_modeling.py:91:1: W191 indentation contains tabs
news-article-nlp/tests/test_topic_modeling.py:91:5: E128 continuation line under-indented for visual indent
news-article-nlp/tests/test_topic_modeling.py:92:1: W191 indentation contains tabs
news-article-nlp/tests/test_topic_modeling.py:92:80: E501 line too long (86 > 79 characters)
news-article-nlp/tests/test_topic_modeling.py:92:86: E502 the backslash is redundant between brackets
news-article-nlp/tests/test_topic_modeling.py:93:1: W191 indentation contains tabs
news-article-nlp/tests/test_topic_modeling.py:93:4: E128 continuation line under-indented for visual indent
news-article-nlp/tests/test_topic_modeling.py:94:1: W191 indentation contains tabs
news-article-nlp/tests/test_topic_modeling.py:95:1: W191 indentation contains tabs
news-article-nlp/tests/test_topic_modeling.py:95:80: E501 line too long (88 > 79 characters)
news-article-nlp/tests/test_topic_modeling.py:95:89: W291 trailing whitespace
news-article-nlp/tests/test_topic_modeling.py:96:1: W191 indentation contains tabs
news-article-nlp/tests/test_topic_modeling.py:96:4: E128 continuation line under-indented for visual indent
news-article-nlp/tests/test_topic_modeling.py:97:1: W191 indentation contains tabs
news-article-nlp/tests/test_topic_modeling.py:97:51: W291 trailing whitespace
news-article-nlp/tests/test_topic_modeling.py:98:1: W191 indentation contains tabs
news-article-nlp/tests/test_topic_modeling.py:98:4: E128 continuation line under-indented for visual indent
news-article-nlp/tests/test_topic_modeling.py:99:1: W191 indentation contains tabs
news-article-nlp/tests/test_topic_modeling.py:101:1: E305 expected 2 blank lines after class or function definition, found 1
news-article-nlp/tests/test_topic_modeling.py:102:1: E101 indentation contains mixed spaces and tabs
news-article-nlp/tests/test_topic_modeling.py:102:20: W292 no newline at end of file

**Comment by heybaebae** [comment]
has issues with the first error:
news-article-nlp/tests/test_handler.py:6:1: E402 module level import not at top of file

due to our sys.path.append() and importing handler afterwards. Can discuss on Sunday.

**Comment by ceduze** [comment]
I found a fix. Resolved now.
