### ISSUE TITLE
Updates to join_process.py

### ISSUE THREAD

**Issue by pcwright1** [heybaebae/news_analyzer#2]
- Update join_process.py that takes in a DF rather than a path
- Put both KNN function and join_process in one file
@yd4wh

**Comment by yd4wh** [comment]
- joined knn function and join_process into one function get_recommended_articles according to handle naming convention
- updated get_recommended_articles.py to use ResourceLoader.get_corpus function to read in the original article corpus 

**To-do:**
- Need to check if the ResourceLoader class works with get_recommended_articles.py

**Comment by yd4wh** [comment]
handler.py pass through corpus information, updates completed.
