### ISSUE TITLE
Flake8 errors for article_recommender.py

### ISSUE THREAD

**Issue by ceduze** [heybaebae/news_analyzer#5]
news-article-nlp/libraries/article_recommender.py:1:80: E501 line too long (83 > 79 characters)
news-article-nlp/libraries/article_recommender.py:4:80: E501 line too long (92 > 79 characters)
news-article-nlp/libraries/article_recommender.py:5:80: E501 line too long (88 > 79 characters)
news-article-nlp/libraries/article_recommender.py:6:80: E501 line too long (86 > 79 characters)
news-article-nlp/libraries/article_recommender.py:16:1: E302 expected 2 blank lines, found 1
news-article-nlp/libraries/article_recommender.py:17:80: E501 line too long (83 > 79 characters)
news-article-nlp/libraries/article_recommender.py:20:80: E501 line too long (93 > 79 characters)
news-article-nlp/libraries/article_recommender.py:21:80: E501 line too long (92 > 79 characters)
news-article-nlp/libraries/article_recommender.py:24:80: E501 line too long (82 > 79 characters)
news-article-nlp/libraries/article_recommender.py:30:1: E302 expected 2 blank lines, found 1
news-article-nlp/libraries/article_recommender.py:34:80: E501 line too long (87 > 79 characters)
news-article-nlp/libraries/article_recommender.py:42:1: E302 expected 2 blank lines, found 1
news-article-nlp/libraries/article_recommender.py:46:80: E501 line too long (93 > 79 characters)
news-article-nlp/libraries/article_recommender.py:47:80: E501 line too long (92 > 79 characters)

**Comment by yd4wh** [comment]
Comply with pylint and flake8 now for article_recommender.py
