### ISSUE TITLE
Flake8 errors for configs.py

### ISSUE THREAD

**Issue by ceduze** [heybaebae/news_analyzer#6]
news-article-nlp/libraries/configs.py:9:1: E302 expected 2 blank lines, found 1
news-article-nlp/libraries/configs.py:10:1: W191 indentation contains tabs
news-article-nlp/libraries/configs.py:11:1: W191 indentation contains tabs
news-article-nlp/libraries/configs.py:12:1: W191 indentation contains tabs
news-article-nlp/libraries/configs.py:13:1: W191 indentation contains tabs
news-article-nlp/libraries/configs.py:14:1: W191 indentation contains tabs
news-article-nlp/libraries/configs.py:15:1: W191 indentation contains tabs
news-article-nlp/libraries/configs.py:16:1: W191 indentation contains tabs
news-article-nlp/libraries/configs.py:17:1: W191 indentation contains tabs
news-article-nlp/libraries/configs.py:19:1: E305 expected 2 blank lines after class or function definition, found 1
news-article-nlp/libraries/configs.py:28:80: E501 line too long (83 > 79 characters)
news-article-nlp/libraries/configs.py:29:1: W191 indentation contains tabs
news-article-nlp/libraries/configs.py:29:6: E101 indentation contains mixed spaces and tabs
news-article-nlp/libraries/configs.py:30:1: W191 indentation contains tabs
news-article-nlp/libraries/configs.py:30:6: E101 indentation contains mixed spaces and tabs
news-article-nlp/libraries/configs.py:30:80: E501 line too long (81 > 79 characters)
news-article-nlp/libraries/configs.py:31:1: W191 indentation contains tabs
news-article-nlp/libraries/configs.py:31:6: E101 indentation contains mixed spaces and tabs

**Comment by ryanbae89** [comment]
flake8 check on current build shows no errors. assumed to be completed. closing the issue.
