### ISSUE TITLE
Flake8 errors for handler.py

### ISSUE THREAD

**Issue by ceduze** [heybaebae/news_analyzer#7]
news-article-nlp/libraries/handler.py:4:80: E501 line too long (81 > 79 characters)
news-article-nlp/libraries/handler.py:5:80: E501 line too long (81 > 79 characters)
news-article-nlp/libraries/handler.py:8:80: E501 line too long (97 > 79 characters)
news-article-nlp/libraries/handler.py:13:1: E265 block comment should start with '# '
news-article-nlp/libraries/handler.py:24:1: E302 expected 2 blank lines, found 1
news-article-nlp/libraries/handler.py:30:80: E501 line too long (85 > 79 characters)
news-article-nlp/libraries/handler.py:46:80: E501 line too long (80 > 79 characters)
news-article-nlp/libraries/handler.py:52:80: E501 line too long (84 > 79 characters)
news-article-nlp/libraries/handler.py:53:80: E501 line too long (88 > 79 characters)
news-article-nlp/libraries/handler.py:55:9: E265 block comment should start with '# '
news-article-nlp/libraries/handler.py:57:80: E501 line too long (91 > 79 characters)
news-article-nlp/libraries/handler.py:58:80: E501 line too long (87 > 79 characters)
news-article-nlp/libraries/handler.py:65:9: E303 too many blank lines (2)
news-article-nlp/libraries/handler.py:77:80: E501 line too long (88 > 79 characters)
news-article-nlp/libraries/handler.py:92:80: E501 line too long (93 > 79 characters)
news-article-nlp/libraries/handler.py:93:80: E501 line too long (89 > 79 characters)
news-article-nlp/libraries/handler.py:94:80: E501 line too long (88 > 79 characters)
news-article-nlp/libraries/handler.py:109:1: E302 expected 2 blank lines, found 1
news-article-nlp/libraries/handler.py:125:1: E302 expected 2 blank lines, found 1

**Comment by heybaebae** [comment]
completed, module passes all flake8 tests.
