### ISSUE TITLE
flake8 errors for nytimes_article_retriever.py

### ISSUE THREAD

**Issue by ceduze** [heybaebae/news_analyzer#8]
news-article-nlp/libraries/nytimes_article_retriever.py:26:80: E501 line too long (94 > 79 characters)
news-article-nlp/libraries/nytimes_article_retriever.py:33:1: E302 expected 2 blank lines, found 1
news-article-nlp/libraries/nytimes_article_retriever.py:35:80: E501 line too long (80 > 79 characters)
news-article-nlp/libraries/nytimes_article_retriever.py:48:59: E225 missing whitespace around operator
news-article-nlp/libraries/nytimes_article_retriever.py:50:16: E114 indentation is not a multiple of four (comment)
news-article-nlp/libraries/nytimes_article_retriever.py:50:16: E116 unexpected indentation (comment)
news-article-nlp/libraries/nytimes_article_retriever.py:51:16: E114 indentation is not a multiple of four (comment)
news-article-nlp/libraries/nytimes_article_retriever.py:51:16: E116 unexpected indentation (comment)
news-article-nlp/libraries/nytimes_article_retriever.py:55:9: E265 block comment should start with '# '
news-article-nlp/libraries/nytimes_article_retriever.py:57:80: E501 line too long (85 > 79 characters)
news-article-nlp/libraries/nytimes_article_retriever.py:62:48: E225 missing whitespace around operator
news-article-nlp/libraries/nytimes_article_retriever.py:63:67: E225 missing whitespace around operator
news-article-nlp/libraries/nytimes_article_retriever.py:67:1: E302 expected 2 blank lines, found 1
news-article-nlp/libraries/nytimes_article_retriever.py:71:80: E501 line too long (92 > 79 characters)
news-article-nlp/libraries/nytimes_article_retriever.py:74:80: E501 line too long (87 > 79 characters)
news-article-nlp/libraries/nytimes_article_retriever.py:84:55: E222 multiple spaces after operator
news-article-nlp/libraries/nytimes_article_retriever.py:84:80: E501 line too long (93 > 79 characters)
news-article-nlp/libraries/nytimes_article_retriever.py:85:80: E501 line too long (96 > 79 characters)

**Comment by pcwright1** [comment]
Done!
